### ISSUE TITLE
Witchwater interactions with water/lava

### ISSUE THREAD

**Issue by ghost** [LordDeatHunter/FabricaeExNihilo#11]
Versions
Minecraft: 1.19
Fabric: 0.14.8
Fabric API: 0.56.0
Fabrica Ex Nihilo 0.1.4

Description
Both in-world, and via REI, witchwater interactions seem incorrect. Witch + Lava = stone variants, Witch + Water = stone variants.
Assumedly witch + water is supposed to create the dirt variants instead. While using REI there are two witch+water recipes listed with different results.

**Comment by LordDeatHunter** [comment]
Nice find, fixed in 0.1.5
