### ISSUE TITLE
Wrong result ID for the soul soil leaking recipe

### ISSUE THREAD

**Issue by FoggyWizard** [LordDeatHunter/FabricaeExNihilo#14]
Course Dirt gives soul sand instead of soul soil because the result id is for soul sand instead of soul soil. Which, if the intended behaviour, is all well and good, but it's explicitly listed under soul soil in your code formatting and not soul sand.

**Comment by MattiDragon** [comment]
Seems to indeed be an issue. Will be fixed in next release
