### ISSUE TITLE
[1.18.2] Inconsistent Recipes

### ISSUE THREAD

**Issue by MSandro** [LordDeatHunter/FabricaeExNihilo#18]
Sieve has different Percentages of several items in REI.

If I press U on the Iron Mesh:
![image](https://user-images.githubusercontent.com/10937159/179788364-31c7c6f3-6f1e-4517-a7c0-ff3006467fa5.png)
If I press R on the Prismarine Shard:
![image](https://user-images.githubusercontent.com/10937159/179788548-b23c00ac-2d5f-48ba-a976-a266e7a8f679.png)

**Comment by MattiDragon** [comment]
:concern: did I fuck up the tooltips somehow?

**Comment by MSandro** [comment]
> :concern: did I fuck up the tooltips somehow?

I did not change the chance, but if I do the problem still remains.

**Comment by LordDeatHunter** [comment]
I made a change that *might* fix this. Can you give **0.1.7** a try and see if the issue persists?

**Comment by MSandro** [comment]
I can confirm, it was fixed.

**Comment by glitchies** [comment]
This seams to have cropped up again.  In v0.5.0 the recipe for Prismarine Shard says that it is a 30% drop from all waterlogged Mesh. While use of gravel in a water logged Iron Mesh is 5%. (unless this has been fixed in a version not posted.)

**Comment by KonSola5** [comment]
I think I found the source of the bug:
If multiple sieving recipes for the same item show up in REI, the tooltip shows the chance of the last recipe rendered.

For example: The prismarine sieving recipe in Sky FABRICation 3:
Its chances should be:

- 5% chance for the Iron Mesh,
- 30% chance for the Diamond Mesh,
- 40% chance for the Netherite Mesh.

Window maximized, shows 3 recipes with Iron Mesh one being the last one:
![maximized](https://user-images.githubusercontent.com/125081901/230561917-2b21617a-fa86-49eb-9106-5954a3e711fa.png)
Window minimized, shows only a Netherite Mesh sieving recipe:
![minimized](https://user-images.githubusercontent.com/125081901/230562050-bccf8569-9209-4ad5-a488-14e21c32a5fd.png)
