### ISSUE TITLE
[1.19] No recipes for melon and pumpkin seeds

### ISSUE THREAD

**Issue by Geartwo** [LordDeatHunter/FabricaeExNihilo#21]
REI says there is no recipe to get melon or pumpkin seeds.
So there is no way in a normal Skyblock world to get them.

**Comment by salianifo** [comment]
Wandering Traders provide access to melon and pumpkin seeds, though it could take a long time to actually get them. [https://minecraft.fandom.com/wiki/Trading#Wandering_trader](https://minecraft.fandom.com/wiki/Trading#Wandering_trader)

**Comment by MattiDragon** [comment]
I wouldn't consider wandering traders a viable alternative to FEN. They are too rare and random

**Comment by LordDeatHunter** [comment]
Making a release for it soon.
