### ISSUE TITLE
[1.18.2] Missing Witchwater Texture on sides?

### ISSUE THREAD

**Issue by 0gp** [LordDeatHunter/FabricaeExNihilo#24]
![image](https://user-images.githubusercontent.com/62187599/182188134-47a58412-37c6-4f3f-943c-e109ff56eb90.png)

**Comment by LordDeatHunter** [comment]
It shouldn't be. What version of the mod were you using?
![image](https://user-images.githubusercontent.com/26803198/185736327-b457d59e-1245-4c65-8ccc-1e5bb53a0c41.png)

**Comment by MattiDragon** [comment]
Closing this as there hasn't been any response
