### ISSUE TITLE
Incompatibility with Sodium

### ISSUE THREAD

**Issue by cryxli** [LordDeatHunter/FabricaeExNihilo#28]
## Observation

When clicking a (stone) barrel with a full water bucket, the game crashes.

[crash-2022-08-21_10.13.40-client.txt](https://github.com/LordDeatHunter/FabricaeExNihilo/files/9388677/crash-2022-08-21_10.13.40-client.txt)

## Setup

- Java 17
- Minecraft 1.18.2
- [Fabric API 0.58.0 1.18.2](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3891301)
- [Cloth Config 6.2.26](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3782775)
- [Ex Nihilo 0.1.7 mc1.18.2](https://www.curseforge.com/minecraft/mc-mods/fabricae-ex-nihilo/files/3943185)
- [Sodium 1.18.2 0.4.1](https://www.curseforge.com/minecraft/mc-mods/sodium/files/3669187)

1. Create a new world (in creative)
2. Get a barrel and a water bucket
3. Place barrel
4. Click barrel with (full) water bucket

## Work Around

Remove/do not use Na.

Once a barrel with water is in render distance the world does not load anymore. Removing Na allows the world to load and play normally.

## Notes

It looks like the Na rendering changes infer with a fluid look-up when rendering liquids in barrels.

Na is not without quirks, but it is used so widely that ensuring compat with it may be a good approach.

I only tested the problem with 1.18.2, but I assume that Na changes fluid rendering in 1.19+, too. 

I'm so happy that someone recreated Ex Nihilo for Fabric. Keep it up!

Cheers
cryxli

**Comment by LordDeatHunter** [comment]
I don't recommend playing modded Minecraft with **just** Sodium, since it breaks a lot of mods. Try installing Indium as well, since it makes Sodium more compatible with other mods, and if the problem persists, you can reopen the issue.
