### ISSUE TITLE
Most Hammering Recipes Don't Work

### ISSUE THREAD

**Issue by Jurklein** [LordDeatHunter/FabricaeExNihilo#30]
When testing the mod, I could not successfully break any of the blocks listed under the hammering recipies folder, only those of the cobblestone-down-to-dust path.

Tested with different hammers, no result.

**Comment by MattiDragon** [comment]
Could you send video or images of breaking blocks with hammers? Also log would be nice

**Comment by MattiDragon** [comment]
Closing this as there hasn't been any response
