### ISSUE TITLE
1.18.2 The result does not exist.

### ISSUE THREAD

**Issue by keulraenoa** [LordDeatHunter/FabricaeExNihilo#32]
hammering/stone/blackstone
hammering/stone/cobbled_deepslate

The above two lists do not produce normal results.

version "wraith-fabricaeexnihilo-0.1.7+mc1.18.2.jar"

**Comment by MattiDragon** [comment]
The crushed blackstone and deepslate are only available with mythic metals. The actual issue is that the recipes aren't disabled when mythic metals isn't installed. I'll fix this in the next update
