### ISSUE TITLE
[1.19.2] Request for Gobber ore drop compatibility 

### ISSUE THREAD

**Issue by kwpugh** [LordDeatHunter/FabricaeExNihilo#33]
hello,

Very nice mod.  Would you consider adding compatibility with my Gobber mod, so there are drops for the gobber ore drops?

https://www.curseforge.com/minecraft/mc-mods/gobber-fabric

https://github.com/kwpugh/gobber_fabric/tree/1.19.2/src/main/java/com/kwpugh/gobber2

Compatibility would be awesome.

Thank you for considering.

Regards,

kwpugh

**Comment by MattiDragon** [comment]
We would probably accept a pull request implementing compat if you want to do it.
