### ISSUE TITLE
[1.19.2] Unable to login to server

### ISSUE THREAD

**Issue by kwpugh** [LordDeatHunter/FabricaeExNihilo#34]
I tried running the mod on my test server and couldn't log in.

server log:  https://gist.github.com/kwpugh/86c117d32be7855460e82d9e14a9da3c

Mod:  wraith-fabricaeexnihilo-0.1.8+mc1.19.2.jar

Works fine in single player.

Let me know if you need anything else.

**Comment by MattiDragon** [comment]
Just pushed a commit fixing this. Will be in the next update
