### ISSUE TITLE
[1.19.2] Mythic Metals raw ore piece sieve recipes don't load

### ISSUE THREAD

**Issue by azaquaz** [LordDeatHunter/FabricaeExNihilo#35]
Minecraft: 1.19.2
Fabric: 0.14.9
FabricaeExNihilo: 0.1.8+mc1.19.2
Mythic Metals: 0.16.2+1.19.2

The items appear fine in REI and can be crafted into raw ores.

**Comment by azaquaz** [comment]
The console outputs a large number of errors upon loading a world which I think are relevant:
[Small excerpt, they are all the same as these but with different recipe ids](https://pastebin.com/AE66cmrW)

**Comment by MattiDragon** [comment]
I probably forgot to migrate them to the new recipe syntax. The previous version should work

**Comment by MattiDragon** [comment]
Pushed a commit fixing this. Will be in next release
