### ISSUE TITLE
(Suggestion) Adding support for EMI

### ISSUE THREAD

**Issue by Qonsyuma** [LordDeatHunter/FabricaeExNihilo#37]
Would be awesome if you could see what you can get out of sieves in EMI (https://modrinth.com/mod/emi) just as it currently works in REI.

**Comment by OldBlackk** [comment]
jei ！！！

**Comment by MSandro** [comment]
Some mods requiring REI, so I can't replace it with EMI, sorry

**Comment by MattiDragon** [comment]
EMI support was added in one of the 1.0.0 betas for 1.20
