### ISSUE TITLE
(Bug) (1.19.2) oak crucible closed my world and I can't load in.

### ISSUE THREAD

**Issue by Hellsinger222** [LordDeatHunter/FabricaeExNihilo#38]
I just placed the oak crucible and put oak leaves in it, the save closed and it keeps closing now.

**Comment by MattiDragon** [comment]
Can I have logs please? Put them on pastebin or something. The game is probably crashing, but catching it and recovering

**Comment by Hellsinger222** [comment]
> Can I have logs please? Put them on pastebin or something. The game is probably crashing, but catching it and recovering

I managed to load in for a second and was able to break the barrel, now I am having the same problem with a stone barrel and lava.
[crash-2022-10-25_13.33.47-client.txt](https://github.com/LordDeatHunter/FabricaeExNihilo/files/9862630/crash-2022-10-25_13.33.47-client.txt)
[crash-2022-10-24_14.11.44-client.txt](https://github.com/LordDeatHunter/FabricaeExNihilo/files/9862631/crash-2022-10-24_14.11.44-client.txt)

**Comment by LordDeatHunter** [comment]
Seems like you have Sodium installed without Indium.
Sodium, by itself, breaks a lot of mods, and [Indium](https://www.curseforge.com/minecraft/mc-mods/indium) fixes most of these issues.

**Comment by Hellsinger222** [comment]
> Seems like you have Sodium installed without Indium. Sodium, by itself, breaks a lot of mods, and [Indium](https://www.curseforge.com/minecraft/mc-mods/indium) fixes most of these issues.

Thank you! Also I feel stupid now...
