### ISSUE TITLE
Milk fluid causes problems

### ISSUE THREAD

**Issue by TropheusJ** [LordDeatHunter/FabricaeExNihilo#40]
I've got a library that adds a milk fluid since it's a somewhat common thing mods add or use: https://github.com/TropheusJ/milk-lib
FabricaeExNihilo adds it's own, and registers a provider to the milk bucket [here](https://github.com/LordDeatHunter/FabricaeExNihilo/blob/2cbf859febbfe21eb1e680c5658d418686d582ce/src/main/java/wraith/fabricaeexnihilo/modules/fluids/MilkFluid.java#L31).
This causes a crash with my library and any mods that use it. There's 2 solutions:
- use milk lib. I can't imagine the transition being difficult. The library is meant to be jar-in-jar'd and the repo has instructions. Bonus of only 1 milk fluid.
- register with FluidStorage.combinedItemApiProvider instead. Pretty sure it will function identically.

original issue: https://github.com/TropheusJ/milk-lib/issues/5

**Comment by EightBlade** [comment]
Did this get fixed?

**Comment by MattiDragon** [comment]
I don't think so. I'll ask DH if they can look into it
