### ISSUE TITLE
Flowing Witchwater Not Pushing Objects

### ISSUE THREAD

**Issue by porl** [LordDeatHunter/FabricaeExNihilo#45]
Flowing witchwater no longer pushes items and mobs (and players).

Mod version 1.7 behaves correctly, 1.8 no longer pushes anything.

Checking a diff between commit 9b0f428 and 4f921ab4 doesn't show anything obvious to me, but I only quickly skimmed through it.

**Comment by MattiDragon** [comment]
This is probably due to me removing the water tag that was causing other issues. 1.20 version will be somewhat patched. Looking into using a library to do this properly
