### ISSUE TITLE
[CRASH] ExNihiloSequentia-0.1.10 mc1.19.3 

### ISSUE THREAD

**Issue by DarcMage** [LordDeatHunter/FabricaeExNihilo#46]
Minecraft Version
1.19.3

Version:
0.1.10

Current Behavior
Error while moving with clay

Expected Behavior
Continue normally

Steps to Reproduce
I was walking and happen to crash.

[crash-2023-04-18_22.25.35-client.txt](https://github.com/LordDeatHunter/FabricaeExNihilo/files/11268216/crash-2023-04-18_22.25.35-client.txt)
[latest.log](https://github.com/LordDeatHunter/FabricaeExNihilo/files/11268217/latest.log)

**Comment by DarcMage** [comment]
![image](https://user-images.githubusercontent.com/106099779/232959784-e2aefe42-55bd-4f0d-9d4c-ebe0fe6c0d8c.png)

**Comment by MattiDragon** [comment]
You are probably using sodium, but not indium. Installing that should fix the issue
