### ISSUE TITLE
Witchwater "processing" text is wrong

### ISSUE THREAD

**Issue by jshipley** [LordDeatHunter/FabricaeExNihilo#49]
When I put a barrel of water on top of a mycelium block, the barrel text (in Jade) displays as "fabricaeexnihilo.hud.hud.alchemy.processing"

There's a typo, and there should only be one ".hud" there so that the text gets replaced with "Transforming: N%"

**Comment by MattiDragon** [comment]
This has been fixed in the upcoming 1.20 version. I don't have time to work on older versions right now and DH also seems quite busy
