### ISSUE TITLE
[1.20.1] Built-in fluid conversions don't seem to work in 1.20.1

### ISSUE THREAD

**Issue by okdewit** [LordDeatHunter/FabricaeExNihilo#56]
### Versions:
wraith-fabricaeexnihilo-1.0.0-beta.4+mc1.20.1
fabric 0.14.23
minecraft 1.20.1

### Details:

* The fluid conversions for milk to slime & water to witchwater do not seem to work.
* The _alchemy_ recipe with an ancient spore for witchwater does work
* There are no relevant errors in the log
* If I add a recipe with KubeJS with just `fluid_in`, it _does_ work, but that doesn't replicate the witchwater recipe correctly, because it would convert the water even when the barrel is on grass.
* If I add a recipe with KubeJS with `block_below`, it _doesn't_ work.
```js
    event.custom({
        'type': 'fabricaeexnihilo:barrel',
        'trigger': { 'type': 'tick' },
        'duration': 200,
        'conditions': [
            {
                'type': 'fluid_in',
                'fluid': 'minecraft:water'
            },
            {
                'type': 'block_below',
                'block': 'minecraft:mycelium'
            }
        ],
        'actions': [
            {
                'type': 'store_fluid',
                'amount': 81000,
                'fluid': {
                    'type': 'fabricaeexnihilo:witchwater'
                }
            }
        ],
        'icon': 'fabricaeexnihilo:witchwater'
    })
```

### Screenshots

![image](https://github.com/LordDeatHunter/FabricaeExNihilo/assets/1403548/ba3c1c2b-90b2-4a2e-92d6-c0d9010486de)
![image](https://github.com/LordDeatHunter/FabricaeExNihilo/assets/1403548/7b12b1be-63c7-4c5f-a294-42dbb64c47f8)

**Comment by MattiDragon** [comment]
Fixed in v1.0.0
