### ISSUE TITLE
[1.20.1] Barrels are broken in many ways.

### ISSUE THREAD

**Issue by KonSola5** [LordDeatHunter/FabricaeExNihilo#57]
## Versions:

- wraith-fabricaeexnihilo-1.0.0-beta.4+mc1.20.1
- Fabric 0.14.23
- Fabric API 0.91.0+1.20.1
- Minecraft 1.20.1

## Details:

- You can continue inserting items to the barrel after it's full.
- Same issue if automation inserts items.
- Automation can't extract the product.
- Trying to automate the barrel completely breaks it (and future barrels), unless you do `/reload`.
- Clicking on a barrel with a block can place the block.

[Link to the video](https://cdn.discordapp.com/attachments/929770432217899058/1186641091429138453/FEN_silkworm.mp4?ex=6593fca2&is=658187a2&hm=36d9cf0f7e9da4d04aaa1aa348e6a1cace2c7d7948f932824bf3e05c0b591236&)

**Comment by MattiDragon** [comment]
Fixed in v1.0.0
