### ISSUE TITLE
Endstone and gravel flipped around

### ISSUE THREAD

**Issue by meijerivoi** [LordDeatHunter/FabricaeExNihilo#63]
It seems that the sieve recipes at `main/resources/data/fabricaeexnihilo/recipes/compat/common` titanium_from_gravel, platinum_from_gravel and uranium_from_crushed_endstone have wrong tags. I'm not totally sure that I understand the json, but it looks like the titanium and platinum from gravel recipes actually give platinum from endstone, and the uranium from endstone recipe gives uranium from gravel.

**Comment by MattiDragon** [comment]
Fixed in v1.0.0
