### ISSUE TITLE
1.20.1 REI Support 

### ISSUE THREAD

**Issue by kgboom3r** [LordDeatHunter/FabricaeExNihilo#64]
Hello! I can't see any information on sieve % to know what the best mesh is to use for what I want. In 1.19.2, I had no issues with REI showing this information, but nothing shows in 1.20.1. Can that be fixed? Not sure what compatibility issues would be caused by other mods, but seems impossible to find details on the percents with REI.

**Comment by MattiDragon** [comment]
Have you updated to v1.0.0? I recently fixed a bug causing sieving recipes to not load in REI

**Comment by kgboom3r** [comment]
Oh, great! I didn't notice there was an update, that fixed it! It did weirdly break being able to launch my instance in Prism as it kept saying I needed 0.15.10 Fabric API to use the new version, which I already have installed. But was able to copy the instance over to Curse Forge and was able to launch the game and can confirm I see the mesh details now. Thank you so much for the quick turnaround in support!! :D
